// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pub_prop.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from pub_prop.proto</summary>
public static partial class PubPropReflection {

  #region Descriptor
  /// <summary>File descriptor for pub_prop.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PubPropReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5wdWJfcHJvcC5wcm90bxoPcHViX3Byb3RvLnByb3RvIjQKCmF3YXJkX2xv",
          "Z3MSDAoEZnJvbRgBIAEoCRIYCgRpdGVtGAIgAygLMgouYXdhcmRfbG9nImAK",
          "CWF3YXJkX2xvZxIMCgR0eXBlGAEgASgJEg8KB2lzX21haWwYAiABKAUSCwoD",
          "c2lkGAMgASgFEgsKA3VpZBgEIAEoAxILCgNudW0YBSABKAMSDQoFYXR0cnMY",
          "BiABKAwiZwoJY2FyZF9hdHRyEgwKBHN0YXIYASABKAMSDAoEc3RlcBgCIAEo",
          "AxINCgVsZXZlbBgDIAEoAxIMCgRza2luGAUgASgDEiEKB2VxdWlwX2wYBCAD",
          "KAsyEC5jYXJkX2VxdWlwX2F0dHIiQwoIcGV0X2F0dHISDAoEc3RhchgBIAEo",
          "AxIMCgRzdGVwGAIgASgDEg0KBWxldmVsGAMgASgDEgwKBHNraW4YBSABKAMi",
          "SQoPY2FyZF9lcXVpcF9hdHRyEg0KBWxldmVsGAEgASgDEhMKC2VuaGFuY2Vt",
          "ZW50GAIgASgDEhIKCmZhaWxfdGltZXMYAyABKAMiQgoVYW5jaWVudF90cmVh",
          "c3VyZV9hdHRyEg0KBWxldmVsGAEgASgDEgwKBHN0YXIYAiABKAMSDAoEc3Rl",
          "cBgDIAEoA2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::PubProtoReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::award_logs), global::award_logs.Parser, new[]{ "From", "Item" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::award_log), global::award_log.Parser, new[]{ "Type", "IsMail", "Sid", "Uid", "Num", "Attrs" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::card_attr), global::card_attr.Parser, new[]{ "Star", "Step", "Level", "Skin", "EquipL" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::pet_attr), global::pet_attr.Parser, new[]{ "Star", "Step", "Level", "Skin" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::card_equip_attr), global::card_equip_attr.Parser, new[]{ "Level", "Enhancement", "FailTimes" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::ancient_treasure_attr), global::ancient_treasure_attr.Parser, new[]{ "Level", "Star", "Step" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 奖励日志
/// </summary>
public sealed partial class award_logs : pb::IMessage<award_logs>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<award_logs> _parser = new pb::MessageParser<award_logs>(() => new award_logs());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<award_logs> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PubPropReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public award_logs() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public award_logs(award_logs other) : this() {
    from_ = other.from_;
    item_ = other.item_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public award_logs Clone() {
    return new award_logs(this);
  }

  /// <summary>Field number for the "from" field.</summary>
  public const int FromFieldNumber = 1;
  private string from_ = "";
  /// <summary>
  ///奖励来源
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string From {
    get { return from_; }
    set {
      from_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "item" field.</summary>
  public const int ItemFieldNumber = 2;
  private static readonly pb::FieldCodec<global::award_log> _repeated_item_codec
      = pb::FieldCodec.ForMessage(18, global::award_log.Parser);
  private readonly pbc::RepeatedField<global::award_log> item_ = new pbc::RepeatedField<global::award_log>();
  /// <summary>
  ///奖励内容
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::award_log> Item {
    get { return item_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as award_logs);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(award_logs other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (From != other.From) return false;
    if(!item_.Equals(other.item_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (From.Length != 0) hash ^= From.GetHashCode();
    hash ^= item_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (From.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(From);
    }
    item_.WriteTo(output, _repeated_item_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (From.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(From);
    }
    item_.WriteTo(ref output, _repeated_item_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (From.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(From);
    }
    size += item_.CalculateSize(_repeated_item_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(award_logs other) {
    if (other == null) {
      return;
    }
    if (other.From.Length != 0) {
      From = other.From;
    }
    item_.Add(other.item_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          From = input.ReadString();
          break;
        }
        case 18: {
          item_.AddEntriesFrom(input, _repeated_item_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          From = input.ReadString();
          break;
        }
        case 18: {
          item_.AddEntriesFrom(ref input, _repeated_item_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class award_log : pb::IMessage<award_log>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<award_log> _parser = new pb::MessageParser<award_log>(() => new award_log());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<award_log> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PubPropReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public award_log() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public award_log(award_log other) : this() {
    type_ = other.type_;
    isMail_ = other.isMail_;
    sid_ = other.sid_;
    uid_ = other.uid_;
    num_ = other.num_;
    attrs_ = other.attrs_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public award_log Clone() {
    return new award_log(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private string type_ = "";
  /// <summary>
  ///物品类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Type {
    get { return type_; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_mail" field.</summary>
  public const int IsMailFieldNumber = 2;
  private int isMail_;
  /// <summary>
  ///是否是发送的邮件:0背包,1=邮件
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsMail {
    get { return isMail_; }
    set {
      isMail_ = value;
    }
  }

  /// <summary>Field number for the "sid" field.</summary>
  public const int SidFieldNumber = 3;
  private int sid_;
  /// <summary>
  ///物品sid
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Sid {
    get { return sid_; }
    set {
      sid_ = value;
    }
  }

  /// <summary>Field number for the "uid" field.</summary>
  public const int UidFieldNumber = 4;
  private long uid_;
  /// <summary>
  ///唯一物品才有的UID,资源类型是总数量
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Uid {
    get { return uid_; }
    set {
      uid_ = value;
    }
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 5;
  private long num_;
  /// <summary>
  ///物品的数量,资源类型是当前变动数量
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Num {
    get { return num_; }
    set {
      num_ = value;
    }
  }

  /// <summary>Field number for the "attrs" field.</summary>
  public const int AttrsFieldNumber = 6;
  private pb::ByteString attrs_ = pb::ByteString.Empty;
  /// <summary>
  ///物品属性 k:属性类型 v:属性值;
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Attrs {
    get { return attrs_; }
    set {
      attrs_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as award_log);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(award_log other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (IsMail != other.IsMail) return false;
    if (Sid != other.Sid) return false;
    if (Uid != other.Uid) return false;
    if (Num != other.Num) return false;
    if (Attrs != other.Attrs) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type.Length != 0) hash ^= Type.GetHashCode();
    if (IsMail != 0) hash ^= IsMail.GetHashCode();
    if (Sid != 0) hash ^= Sid.GetHashCode();
    if (Uid != 0L) hash ^= Uid.GetHashCode();
    if (Num != 0L) hash ^= Num.GetHashCode();
    if (Attrs.Length != 0) hash ^= Attrs.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Type);
    }
    if (IsMail != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(IsMail);
    }
    if (Sid != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Sid);
    }
    if (Uid != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Uid);
    }
    if (Num != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Num);
    }
    if (Attrs.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(Attrs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Type);
    }
    if (IsMail != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(IsMail);
    }
    if (Sid != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Sid);
    }
    if (Uid != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Uid);
    }
    if (Num != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Num);
    }
    if (Attrs.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(Attrs);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
    }
    if (IsMail != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsMail);
    }
    if (Sid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sid);
    }
    if (Uid != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
    }
    if (Num != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Num);
    }
    if (Attrs.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Attrs);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(award_log other) {
    if (other == null) {
      return;
    }
    if (other.Type.Length != 0) {
      Type = other.Type;
    }
    if (other.IsMail != 0) {
      IsMail = other.IsMail;
    }
    if (other.Sid != 0) {
      Sid = other.Sid;
    }
    if (other.Uid != 0L) {
      Uid = other.Uid;
    }
    if (other.Num != 0L) {
      Num = other.Num;
    }
    if (other.Attrs.Length != 0) {
      Attrs = other.Attrs;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Type = input.ReadString();
          break;
        }
        case 16: {
          IsMail = input.ReadInt32();
          break;
        }
        case 24: {
          Sid = input.ReadInt32();
          break;
        }
        case 32: {
          Uid = input.ReadInt64();
          break;
        }
        case 40: {
          Num = input.ReadInt64();
          break;
        }
        case 50: {
          Attrs = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Type = input.ReadString();
          break;
        }
        case 16: {
          IsMail = input.ReadInt32();
          break;
        }
        case 24: {
          Sid = input.ReadInt32();
          break;
        }
        case 32: {
          Uid = input.ReadInt64();
          break;
        }
        case 40: {
          Num = input.ReadInt64();
          break;
        }
        case 50: {
          Attrs = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///%%卡牌数据
/// </summary>
public sealed partial class card_attr : pb::IMessage<card_attr>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<card_attr> _parser = new pb::MessageParser<card_attr>(() => new card_attr());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<card_attr> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PubPropReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public card_attr() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public card_attr(card_attr other) : this() {
    star_ = other.star_;
    step_ = other.step_;
    level_ = other.level_;
    skin_ = other.skin_;
    equipL_ = other.equipL_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public card_attr Clone() {
    return new card_attr(this);
  }

  /// <summary>Field number for the "star" field.</summary>
  public const int StarFieldNumber = 1;
  private long star_;
  /// <summary>
  ///星级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Star {
    get { return star_; }
    set {
      star_ = value;
    }
  }

  /// <summary>Field number for the "step" field.</summary>
  public const int StepFieldNumber = 2;
  private long step_;
  /// <summary>
  ///阶级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Step {
    get { return step_; }
    set {
      step_ = value;
    }
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 3;
  private long level_;
  /// <summary>
  ///等级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "skin" field.</summary>
  public const int SkinFieldNumber = 5;
  private long skin_;
  /// <summary>
  ///皮肤
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Skin {
    get { return skin_; }
    set {
      skin_ = value;
    }
  }

  /// <summary>Field number for the "equip_l" field.</summary>
  public const int EquipLFieldNumber = 4;
  private static readonly pb::FieldCodec<global::card_equip_attr> _repeated_equipL_codec
      = pb::FieldCodec.ForMessage(34, global::card_equip_attr.Parser);
  private readonly pbc::RepeatedField<global::card_equip_attr> equipL_ = new pbc::RepeatedField<global::card_equip_attr>();
  /// <summary>
  ///装备数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::card_equip_attr> EquipL {
    get { return equipL_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as card_attr);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(card_attr other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Star != other.Star) return false;
    if (Step != other.Step) return false;
    if (Level != other.Level) return false;
    if (Skin != other.Skin) return false;
    if(!equipL_.Equals(other.equipL_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Star != 0L) hash ^= Star.GetHashCode();
    if (Step != 0L) hash ^= Step.GetHashCode();
    if (Level != 0L) hash ^= Level.GetHashCode();
    if (Skin != 0L) hash ^= Skin.GetHashCode();
    hash ^= equipL_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Star != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Star);
    }
    if (Step != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Step);
    }
    if (Level != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Level);
    }
    equipL_.WriteTo(output, _repeated_equipL_codec);
    if (Skin != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Skin);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Star != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Star);
    }
    if (Step != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Step);
    }
    if (Level != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Level);
    }
    equipL_.WriteTo(ref output, _repeated_equipL_codec);
    if (Skin != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Skin);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Star != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Star);
    }
    if (Step != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Step);
    }
    if (Level != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Level);
    }
    if (Skin != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Skin);
    }
    size += equipL_.CalculateSize(_repeated_equipL_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(card_attr other) {
    if (other == null) {
      return;
    }
    if (other.Star != 0L) {
      Star = other.Star;
    }
    if (other.Step != 0L) {
      Step = other.Step;
    }
    if (other.Level != 0L) {
      Level = other.Level;
    }
    if (other.Skin != 0L) {
      Skin = other.Skin;
    }
    equipL_.Add(other.equipL_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Star = input.ReadInt64();
          break;
        }
        case 16: {
          Step = input.ReadInt64();
          break;
        }
        case 24: {
          Level = input.ReadInt64();
          break;
        }
        case 34: {
          equipL_.AddEntriesFrom(input, _repeated_equipL_codec);
          break;
        }
        case 40: {
          Skin = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Star = input.ReadInt64();
          break;
        }
        case 16: {
          Step = input.ReadInt64();
          break;
        }
        case 24: {
          Level = input.ReadInt64();
          break;
        }
        case 34: {
          equipL_.AddEntriesFrom(ref input, _repeated_equipL_codec);
          break;
        }
        case 40: {
          Skin = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///神力值  pub_proto single_int 时间戳
/// 神宠数据
/// </summary>
public sealed partial class pet_attr : pb::IMessage<pet_attr>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<pet_attr> _parser = new pb::MessageParser<pet_attr>(() => new pet_attr());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<pet_attr> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PubPropReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pet_attr() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pet_attr(pet_attr other) : this() {
    star_ = other.star_;
    step_ = other.step_;
    level_ = other.level_;
    skin_ = other.skin_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pet_attr Clone() {
    return new pet_attr(this);
  }

  /// <summary>Field number for the "star" field.</summary>
  public const int StarFieldNumber = 1;
  private long star_;
  /// <summary>
  ///星级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Star {
    get { return star_; }
    set {
      star_ = value;
    }
  }

  /// <summary>Field number for the "step" field.</summary>
  public const int StepFieldNumber = 2;
  private long step_;
  /// <summary>
  ///阶级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Step {
    get { return step_; }
    set {
      step_ = value;
    }
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 3;
  private long level_;
  /// <summary>
  ///等级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "skin" field.</summary>
  public const int SkinFieldNumber = 5;
  private long skin_;
  /// <summary>
  ///皮肤
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Skin {
    get { return skin_; }
    set {
      skin_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as pet_attr);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(pet_attr other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Star != other.Star) return false;
    if (Step != other.Step) return false;
    if (Level != other.Level) return false;
    if (Skin != other.Skin) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Star != 0L) hash ^= Star.GetHashCode();
    if (Step != 0L) hash ^= Step.GetHashCode();
    if (Level != 0L) hash ^= Level.GetHashCode();
    if (Skin != 0L) hash ^= Skin.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Star != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Star);
    }
    if (Step != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Step);
    }
    if (Level != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Level);
    }
    if (Skin != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Skin);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Star != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Star);
    }
    if (Step != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Step);
    }
    if (Level != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Level);
    }
    if (Skin != 0L) {
      output.WriteRawTag(40);
      output.WriteInt64(Skin);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Star != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Star);
    }
    if (Step != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Step);
    }
    if (Level != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Level);
    }
    if (Skin != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Skin);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pet_attr other) {
    if (other == null) {
      return;
    }
    if (other.Star != 0L) {
      Star = other.Star;
    }
    if (other.Step != 0L) {
      Step = other.Step;
    }
    if (other.Level != 0L) {
      Level = other.Level;
    }
    if (other.Skin != 0L) {
      Skin = other.Skin;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Star = input.ReadInt64();
          break;
        }
        case 16: {
          Step = input.ReadInt64();
          break;
        }
        case 24: {
          Level = input.ReadInt64();
          break;
        }
        case 40: {
          Skin = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Star = input.ReadInt64();
          break;
        }
        case 16: {
          Step = input.ReadInt64();
          break;
        }
        case 24: {
          Level = input.ReadInt64();
          break;
        }
        case 40: {
          Skin = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// 武将装备数据
/// </summary>
public sealed partial class card_equip_attr : pb::IMessage<card_equip_attr>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<card_equip_attr> _parser = new pb::MessageParser<card_equip_attr>(() => new card_equip_attr());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<card_equip_attr> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PubPropReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public card_equip_attr() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public card_equip_attr(card_equip_attr other) : this() {
    level_ = other.level_;
    enhancement_ = other.enhancement_;
    failTimes_ = other.failTimes_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public card_equip_attr Clone() {
    return new card_equip_attr(this);
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 1;
  private long level_;
  /// <summary>
  ///等级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "enhancement" field.</summary>
  public const int EnhancementFieldNumber = 2;
  private long enhancement_;
  /// <summary>
  ///强化等级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Enhancement {
    get { return enhancement_; }
    set {
      enhancement_ = value;
    }
  }

  /// <summary>Field number for the "fail_times" field.</summary>
  public const int FailTimesFieldNumber = 3;
  private long failTimes_;
  /// <summary>
  ///强化失败次数
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long FailTimes {
    get { return failTimes_; }
    set {
      failTimes_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as card_equip_attr);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(card_equip_attr other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Level != other.Level) return false;
    if (Enhancement != other.Enhancement) return false;
    if (FailTimes != other.FailTimes) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Level != 0L) hash ^= Level.GetHashCode();
    if (Enhancement != 0L) hash ^= Enhancement.GetHashCode();
    if (FailTimes != 0L) hash ^= FailTimes.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Level != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Level);
    }
    if (Enhancement != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Enhancement);
    }
    if (FailTimes != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(FailTimes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Level != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Level);
    }
    if (Enhancement != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Enhancement);
    }
    if (FailTimes != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(FailTimes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Level != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Level);
    }
    if (Enhancement != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Enhancement);
    }
    if (FailTimes != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(FailTimes);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(card_equip_attr other) {
    if (other == null) {
      return;
    }
    if (other.Level != 0L) {
      Level = other.Level;
    }
    if (other.Enhancement != 0L) {
      Enhancement = other.Enhancement;
    }
    if (other.FailTimes != 0L) {
      FailTimes = other.FailTimes;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Level = input.ReadInt64();
          break;
        }
        case 16: {
          Enhancement = input.ReadInt64();
          break;
        }
        case 24: {
          FailTimes = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Level = input.ReadInt64();
          break;
        }
        case 16: {
          Enhancement = input.ReadInt64();
          break;
        }
        case 24: {
          FailTimes = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// 古宝数据
/// </summary>
public sealed partial class ancient_treasure_attr : pb::IMessage<ancient_treasure_attr>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ancient_treasure_attr> _parser = new pb::MessageParser<ancient_treasure_attr>(() => new ancient_treasure_attr());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ancient_treasure_attr> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PubPropReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ancient_treasure_attr() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ancient_treasure_attr(ancient_treasure_attr other) : this() {
    level_ = other.level_;
    star_ = other.star_;
    step_ = other.step_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ancient_treasure_attr Clone() {
    return new ancient_treasure_attr(this);
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 1;
  private long level_;
  /// <summary>
  ///等级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "star" field.</summary>
  public const int StarFieldNumber = 2;
  private long star_;
  /// <summary>
  ///星级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Star {
    get { return star_; }
    set {
      star_ = value;
    }
  }

  /// <summary>Field number for the "step" field.</summary>
  public const int StepFieldNumber = 3;
  private long step_;
  /// <summary>
  ///阶级
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Step {
    get { return step_; }
    set {
      step_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ancient_treasure_attr);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ancient_treasure_attr other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Level != other.Level) return false;
    if (Star != other.Star) return false;
    if (Step != other.Step) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Level != 0L) hash ^= Level.GetHashCode();
    if (Star != 0L) hash ^= Star.GetHashCode();
    if (Step != 0L) hash ^= Step.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Level != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Level);
    }
    if (Star != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Star);
    }
    if (Step != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Step);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Level != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Level);
    }
    if (Star != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(Star);
    }
    if (Step != 0L) {
      output.WriteRawTag(24);
      output.WriteInt64(Step);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Level != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Level);
    }
    if (Star != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Star);
    }
    if (Step != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Step);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ancient_treasure_attr other) {
    if (other == null) {
      return;
    }
    if (other.Level != 0L) {
      Level = other.Level;
    }
    if (other.Star != 0L) {
      Star = other.Star;
    }
    if (other.Step != 0L) {
      Step = other.Step;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Level = input.ReadInt64();
          break;
        }
        case 16: {
          Star = input.ReadInt64();
          break;
        }
        case 24: {
          Step = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Level = input.ReadInt64();
          break;
        }
        case 16: {
          Star = input.ReadInt64();
          break;
        }
        case 24: {
          Step = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
